language: php
php:
  - 7.1
  - 7.2
  - master
matrix:
  allow_failures:
    - php: master
env:
  - BLUZ_MODULE=push
before_install:
  - phpenv config-rm xdebug.ini
install:
  # Composer
  - composer self-update
  - composer create-project bluzphp/skeleton --stability=dev
  # Require current module
  - cd skeleton
  - composer require bluzphp/module-$BLUZ_MODULE:dev-$TRAVIS_BRANCH
before_script:
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  # Migrations
  - php vendor/bin/bluzman db:migrate
  - php vendor/bin/bluzman db:seed:run
script:
  # Check code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # Run built-in web-server
  - php vendor/bin/bluzman server:start --host 127.0.0.1 -b
  # Run CodeCeption tests
  - php vendor/bin/bluzman test module-$BLUZ_MODULE
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
branches:
  only:
  - master
  - develop
