<?php
/** @var \Application\Push\Row $row */
$uid = uniqid('form_', false);
$url = $this->url('push', 'crud');
?>
<form id="<?=$uid?>" action="<?=$url?>" class="form-horizontal" data-ajax method="POST">
  <input type="hidden" name="_method" value="<?=$method?>"/>
  <div class="modal-header">
    <h4 class="modal-title"><?=__('Push')?></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <input type="hidden" id="id" name="id" value="<?= $row['id'] ?>"/>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="userId"><?=__('UserId')?></label>
      <div class="col-lg-8">
        <input type="number" id="userId" name="userId" class="form-control" value="<?= $row['userId'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="authToken"><?=__('AuthToken')?></label>
      <div class="col-lg-8">
        <input type="text" id="authToken" name="authToken" class="form-control" value="<?= $row['authToken'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="contentEncoding"><?=__('ContentEncoding')?></label>
      <div class="col-lg-8">
        <input type="text" id="contentEncoding" name="contentEncoding" class="form-control" value="<?= $row['contentEncoding'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="endpoint"><?=__('Endpoint')?></label>
      <div class="col-lg-8">
        <input type="text" id="endpoint" name="endpoint" class="form-control" value="<?= $row['endpoint'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="publicKey"><?=__('PublicKey')?></label>
      <div class="col-lg-8">
        <input type="text" id="publicKey" name="publicKey" class="form-control" value="<?= $row['publicKey'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="created"><?=__('Created')?></label>
      <div class="col-lg-8">
        <input type="datetime-local" id="created" name="created" class="form-control" disabled value="<?= $row['created'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="updated"><?=__('Updated')?></label>
      <div class="col-lg-8">
        <input type="datetime-local" id="updated" name="updated" class="form-control" disabled value="<?= $row['updated'] ?>"/>
        <div class="invalid-feedback"><!-- Place custom validator message here --></div>
      </div>
    </div>
    <!-- Place additional form fields here -->
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>