<?php
/** @var \Application\Push\Row $row */
$uid = uniqid('form_', false);
$url = $this->url('push', 'send');
?>
<form id="<?=$uid?>" action="<?=$url?>" class="form-horizontal" data-ajax method="POST">
  <input type="hidden" name="_method" value="POST"/>
  <input type="hidden" id="id" name="id" value="<?= $id ?>"/>

<div class="modal-header">
  <h4 class="modal-title"><?= __('Send Web Push Notification') ?></h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="form-group">
    <label for="message"><?=__('Message')?></label>
    <textarea id="message" name="message" class="form-control" maxlength="100"><?=esc($message)?></textarea>
  </div>
</div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
  </div>
</form>