<script>
  require(['jquery', 'bluz.push'], function($, push) {
    $(function() {
      $('#subscribe').on('click', function() {
        push.subscribe()
      });

      $('#unsubscribe').on('click', function() {
        push.unsubscribe()
      });
    })
  });
</script>
<div class="modal-header">
  <h4 class="modal-title"><?= __('Web Push Subscription') ?></h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <button id="subscribe" class="btn btn-primary"><?=__('Subscribe')?></button>
  <button id="unsubscribe" class="btn btn-secondary"><?=__('Unsubscribe')?></button>
</div>
<div class="modal-footer">
  <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
</div>